### ISSUE TITLE
Bytes Length Limit error

### ISSUE THREAD

**Issue by unghuuduc** [radixdlt/babylon-alphanet#25]
![image](https://user-images.githubusercontent.com/55659332/194722997-6b34dab3-2e3a-4355-b415-aa598353e4ba.png)

I was trying to publish my package (1.04 mb) through the alphanet package deployer and got this issue, please take a look.

**Comment by cbisaillon** [comment]
Hey @unghuuduc was this fixed with the new alphanet releases last week?

**Comment by unghuuduc** [comment]
@cbisaillon it worked fine now, will close the issue, thanks!
